// Code generated by mockery v2.12.0. DO NOT EDIT.

package mocks

import (
	context "context"

	sender "github.com/dmalykh/refurbedsender/sender"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// ProceedFunc is an autogenerated mock type for the ProceedFunc type
type ProceedFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, m
func (_m *ProceedFunc) Execute(ctx context.Context, m sender.Message) error {
	ret := _m.Called(ctx, m)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sender.Message) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProceedFunc creates a new instance of ProceedFunc. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewProceedFunc(t testing.TB) *ProceedFunc {
	mock := &ProceedFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
